{{- if and .Values.tenantName .Values.projectName }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "project.projectNamespace" . }}
  labels:
    {{- include "project.labels" . | nindent 4 }}
    tenant.kitkube.dk/name: {{ .Values.tenantName }}
    project.kitkube.dk/name: {{ .Values.projectName }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    helm.sh/resource-policy: keep
    {{- with .Values.namespace.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
